apiVersion: v1
kind: Service
metadata:
  name: mysql-pv
spec:
  ports:
  - port: 3306
    name: mysql-pv
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-pv
spec:
  selector:
    matchLabels:
      app: mysql-pv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-pv
    spec:
      containers:
      - image: mysql:latest
        name: mysql-pv
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql-pv
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim